### PR TITLE
Fixed ready event name for IE < 9 +  Fixed issue with 'interactive' document.readyState 

### PR DESCRIPTION
**Pull request by vittorio**
I fixed wrong event name for IE < 9 which was added in this pr https://github.com/ofirdagan/cross-domain-local-storage/pull/27

Very sorry, my mistake.

Also
document.addEventListener('DOMContentLoaded') doesn't call handler if it was bound while 'interactive' document.readyState. So i changed 'DOMContentLoaded' event to 'readystatechange' with state filter.

### CODE REVIEW

**Comment by ofirdagan** [comment]
released 2.0.5 :)

**Comment by vittorio** [comment]
Thanks

**Comment by vittorio** [comment]
@ofirdagan could you please also update npm and bower versions?

**Comment by ofirdagan** [comment]
updated both at 2.0.5

**Pull request merged**
