### PR TITLE
shek8034: Added localStorage getSize Functionality

### PR DESCRIPTION
**Pull request by shek8034**
There is no way to get the size of localStorage, to check how much localStorage is consumed.
Added getSize() functionality to get the size of locaStorage, which returns the size in bytes.

### CODE REVIEW

**Comment by ofirdagan** [comment]
Hi @shek8034  , I'm sorry for the long delay. From some reason the github mail reached my spam folder.. Now it's fixed :)

Cool feature. I have two requests if it's possible.

1. Add tests
2. Expose the getSize method on the angular service as well.

10x!

**Comment by shek8034** [comment]
Hi @ofirdagan , I didn't get time to write angular code. Also, i have written the unit test for the commit. Just review them and merge this.
Thanks

**Comment by ofirdagan** [comment]
:+1:

**Comment by mattia85** [comment]
Hi @ofirdagan ,
could you release a new version adding this functionality?
Currently latest release doesn't have getSize method.

Thanks

**Comment by ofirdagan** [comment]
@mattia85  - sorry about it. I published it now.

**Pull request merged**
