### PR TITLE
iframeReady start value

### PR DESCRIPTION
**Pull request by felipechierice**
iframeReady start value = false

### CODE REVIEW

**Comment by ofirdagan** [comment]
did u run the tests? I didn't run in it for while. how come u need this change? what happens when it's true?

**Comment by felipechierice** [comment]
If iframeReady starts with true, xdLocalStorage.isApiReady () returns true even if the iframe is not ready yet, then if we call the xdLocalStorage.getItem function or any other with wasInit = true however without the iframe being ready there will be an unforeseen execution error .

**Comment by felipechierice** [comment]
iframeReady should start with false for correct execution. Try to initialize xdLocalStorage, and then call e.g. xdLocalStorage.getItem, you will get an error.

e.g.:

xdLocalStorage.init({
    iframeUrl:'http://act-api.000webhostapp.com/act-xdls/act-xdls-domain.html',
});
xdLocalStorage.setItem('foo', 'bar', function(data) {
    console.log("ok");
});

**Comment by ofirdagan** [comment]
Hey, this change is w/o tests. I'm not maintaining this project anymore and I'm afraid to introduce changes that could cause regressions. Sorry.

**Comment by felipechierice** [comment]
Project not maintained

**Pull request closed without merging**
