### PR TITLE
Fix apiReady resolve

### PR DESCRIPTION
**Pull request by shawila**
Problem [here](https://github.com/ofirdagan/cross-domain-local-storage/pull/15/files#diff-afda7a2f94f5a0c2259931353df7d446L12) is that this `$watch` will fire at the first `$digest` after it is registered, regardless whether `iframeReady` changed or not.

Therefore, the promise was resolved prematurely.
Reference [docs](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch).

### CODE REVIEW

**Comment by shawila** [comment]
We noticed the problem when we tried calling a `getItem` while `init` was still in progress. It was not waiting properly for the `init` to complete.

Furthermore, the check for `iframeReady` would pass even though it was not actually ready and crash later on so also fixed that.

**Comment by mediavrog** [comment]
:+1:

**Comment by ofirdagan** [comment]
Hi @shawila , I'm sorry for the long delay. From some reason the github mail reached my spam folder.. Now it's fixed.

Thanks for the PR and good catch with the bug.. Can u please add a test demonstrates your fix?

**Comment by shawila** [comment]
Hey @ofirdagan I'll do that as soon as I can. Tried a bit yesterday but am super noob with Grunt and couldn't get the tests to run properly.

**Comment by ofirdagan** [comment]
No problem. If u have any specific question I'll be happy to help.

**Comment by Hengjie** [comment]
I've got a better fix than this https://github.com/NotablePDF/cross-domain-local-storage/commit/218c459ae76980005ce9324752da62608738dcf3

**Comment by ofirdagan** [comment]
Cool @Hengjie  - plz add a test for your fix as well so I can merge it.

**Comment by shawila** [comment]
:+1:

**Pull request closed without merging**
